path = "/mnt/c/Users/rakes/OneDrive/Desktop/aiguru/app/src/main/java/com/example/aiguru/ChatActivity.kt"
with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

field_block = (
    "\n"
    "    // \u2500\u2500 Interactive Voice Chat Mode \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "    private var isVoiceModeActive = false\n"
    "    private lateinit var voiceChatButton: MaterialButton\n"
    "    private lateinit var voiceChatBar: LinearLayout\n"
    "    private lateinit var voiceChatStatus: TextView\n"
    "    private lateinit var waveBarContainer: LinearLayout\n"
    "    private lateinit var waveBar1: View\n"
    "    private lateinit var waveBar2: View\n"
    "    private lateinit var waveBar3: View\n"
    "    private lateinit var waveBar4: View\n"
    "    private var currentTTSText = \"\"\n"
    "    private var isInterrupted = false\n"
)

voice_fns = (
    "    private fun startVoiceMode() {\n"
    "        if (ContextCompat.checkSelfPermission(this, android.Manifest.permission.RECORD_AUDIO)\n"
    "            != PackageManager.PERMISSION_GRANTED) {\n"
    "            ActivityCompat.requestPermissions(\n"
    "                this, arrayOf(android.Manifest.permission.RECORD_AUDIO), PERMISSION_REQUEST_CODE\n"
    "            )\n"
    "            return\n"
    "        }\n"
    "        isVoiceModeActive = true\n"
    "        isInterrupted = false\n"
    "        voiceButton.isEnabled = false\n"
    "        voiceChatBar.visibility = View.VISIBLE\n"
    "        listeningIndicator.visibility = View.GONE\n"
    "        voiceChatButton.backgroundTintList = ColorStateList.valueOf(android.graphics.Color.parseColor(\"#E53935\"))\n"
    "        Toast.makeText(this, \"\U0001f399\ufe0f Voice mode ON \u2014 just speak!\", Toast.LENGTH_SHORT).show()\n"
    "        startVoiceLoopListening()\n"
    "    }\n"
    "\n"
    "    private fun stopVoiceMode() {\n"
    "        isVoiceModeActive = false\n"
    "        isInterrupted = false\n"
    "        ttsManager.stop()\n"
    "        voiceManager.stopInterruptListening()\n"
    "        if (isListening) { voiceManager.stopListening(); isListening = false }\n"
    "        stopWaveAnimation()\n"
    "        stopMicPulse()\n"
    "        voiceButton.isEnabled = true\n"
    "        voiceChatBar.visibility = View.GONE\n"
    "        voiceChatButton.backgroundTintList = ColorStateList.valueOf(android.graphics.Color.parseColor(\"#E8F5E9\"))\n"
    "        Toast.makeText(this, \"Voice mode OFF\", Toast.LENGTH_SHORT).show()\n"
    "    }\n"
    "\n"
    "    private fun startVoiceLoopListening() {\n"
    "        if (!isVoiceModeActive) return\n"
    "        isListening = true\n"
    "        setVoiceModeStatus(\"\U0001f399\ufe0f Listening\u2026 speak now\", \"#2E7D32\")\n"
    "        voiceManager.startListening(this, currentLang)\n"
    "        startMicPulse()\n"
    "    }\n"
    "\n"
    "    private fun setVoiceModeStatus(text: String, colorHex: String) {\n"
    "        voiceChatStatus.text = text\n"
    "        voiceChatStatus.setTextColor(android.graphics.Color.parseColor(colorHex))\n"
    "        when (colorHex) {\n"
    "            \"#2E7D32\", \"#6A1B9A\" -> startWaveAnimation(colorHex)\n"
    "            \"#1565C0\"             -> { startWaveAnimation(\"#1565C0\"); stopMicPulse() }\n"
    "            else                  -> { stopWaveAnimation(); stopMicPulse() }\n"
    "        }\n"
    "    }\n"
    "\n"
    "    private val interruptCallback = object : VoiceRecognitionCallback {\n"
    "        override fun onPartialResults(text: String) {\n"
    "            if (!isVoiceModeActive || !ttsManager.isSpeaking() || text.length < 3) return\n"
    "            val normalizedTTS = currentTTSText.lowercase()\n"
    "            if (normalizedTTS.contains(text.lowercase().trim())) return\n"
    "            triggerBargein()\n"
    "        }\n"
    "        override fun onBeginningOfSpeech() {}\n"
    "        override fun onResults(text: String) {\n"
    "            if (!isVoiceModeActive || text.length < 2) return\n"
    "            if (!currentTTSText.lowercase().contains(text.lowercase().trim())) triggerBargein()\n"
    "        }\n"
    "        override fun onError(error: String) {}\n"
    "        override fun onListeningStarted() {}\n"
    "        override fun onListeningFinished() {}\n"
    "    }\n"
    "\n"
    "    private fun triggerBargein() {\n"
    "        if (isInterrupted) return\n"
    "        isInterrupted = true\n"
    "        ttsManager.stop()\n"
    "        voiceManager.stopInterruptListening()\n"
    "        runOnUiThread { setVoiceModeStatus(\"\U0001f399\ufe0f Listening (interrupted)\u2026\", \"#6A1B9A\") }\n"
    "        isListening = true\n"
    "        voiceManager.startListening(this, currentLang)\n"
    "    }\n"
    "\n"
    "    private fun startWaveAnimation(colorHex: String) {\n"
    "        waveBarContainer.visibility = View.VISIBLE\n"
    "        val tint = ColorStateList.valueOf(android.graphics.Color.parseColor(colorHex))\n"
    "        listOf(waveBar1, waveBar2, waveBar3, waveBar4).forEach { it.backgroundTintList = tint }\n"
    "        val durations = longArrayOf(420L, 600L, 360L, 510L)\n"
    "        val delays    = longArrayOf(  0L, 130L, 260L,  80L)\n"
    "        listOf(waveBar1, waveBar2, waveBar3, waveBar4).forEachIndexed { i, bar ->\n"
    "            bar.clearAnimation()\n"
    "            bar.startAnimation(ScaleAnimation(\n"
    "                1f, 1f, 0.15f, 1f,\n"
    "                Animation.RELATIVE_TO_SELF, 0.5f,\n"
    "                Animation.RELATIVE_TO_SELF, 1.0f\n"
    "            ).apply {\n"
    "                duration    = durations[i]\n"
    "                startOffset = delays[i]\n"
    "                repeatMode  = Animation.REVERSE\n"
    "                repeatCount = Animation.INFINITE\n"
    "                fillAfter   = true\n"
    "            })\n"
    "        }\n"
    "    }\n"
    "\n"
    "    private fun stopWaveAnimation() {\n"
    "        listOf(waveBar1, waveBar2, waveBar3, waveBar4).forEach { it.clearAnimation() }\n"
    "        waveBarContainer.visibility = View.GONE\n"
    "    }\n"
    "\n"
    "    private fun startMicPulse() {\n"
    "        voiceButton.clearAnimation()\n"
    "        voiceButton.startAnimation(ScaleAnimation(\n"
    "            1f, 1.15f, 1f, 1.15f,\n"
    "            Animation.RELATIVE_TO_SELF, 0.5f,\n"
    "            Animation.RELATIVE_TO_SELF, 0.5f\n"
    "        ).apply {\n"
    "            duration    = 600L\n"
    "            repeatMode  = Animation.REVERSE\n"
    "            repeatCount = Animation.INFINITE\n"
    "            fillAfter   = true\n"
    "        })\n"
    "    }\n"
    "\n"
    "    private fun stopMicPulse() {\n"
    "        voiceButton.clearAnimation()\n"
    "        voiceButton.scaleX = 1f\n"
    "        voiceButton.scaleY = 1f\n"
    "    }\n"
    "\n"
)

# 1. Insert field declarations after line 92 (0-indexed: 91)
lines.insert(92, field_block)

# 2. Re-find the voice section header line after the first insertion
for i, l in enumerate(lines):
    if 'Interactive Voice Chat Mode (single-shot mic only)' in l:
        voice_header_idx = i
        break

# Insert functions between the header (voice_header_idx) and the blank line before onStop
lines.insert(voice_header_idx + 2, voice_fns)

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Done. Total lines:", len(lines))
