"""
Daily Questions Feed API

Generates, serves, and tracks personalised daily questions for students.
Questions are generated by the LLM based on the student's chat history and
interest profile, stored in Firestore, and surfaced on the Home screen.

Collections:
  daily_questions_feed/{uid}/questions/{qid}
  student_interests/{uid}
"""

from __future__ import annotations

import asyncio
import json
import time
import uuid
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from google.cloud.firestore import Increment

from app.core.auth import require_auth, AuthUser
from app.core.firebase_auth import get_firestore_db
from app.core.logger import get_logger
from app.services.llm_service import generate_response

logger = get_logger(__name__)
router = APIRouter(prefix="/daily-questions", tags=["daily-questions"])

# ── Constants ─────────────────────────────────────────────────────────────────

QUESTIONS_PER_DAY = 3          # how many fresh questions to generate
CREDITS_PER_COMPLETION = 5     # credits awarded for completing a question
QUESTION_TTL_HOURS = 30        # questions expire after this many hours


# ── Helpers ───────────────────────────────────────────────────────────────────

def _now_ms() -> int:
    return int(time.time() * 1000)


def _today_utc() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")


def _is_today(ts_ms: int) -> bool:
    """Return True if ts_ms falls on today's UTC date."""
    try:
        date = datetime.fromtimestamp(ts_ms / 1000, tz=timezone.utc).strftime("%Y-%m-%d")
        return date == _today_utc()
    except Exception:
        return False


def _get_interest_profile(db, uid: str) -> dict:
    """Read student_interests/{uid}. Returns {} if missing."""
    try:
        doc = db.collection("student_interests").document(uid).get()
        return doc.to_dict() if doc.exists else {}
    except Exception as exc:
        logger.warning("_get_interest_profile uid=%s: %s", uid, exc)
        return {}


def _update_interest_profile(db, uid: str, subject: str, topics: list[str]) -> None:
    """Merge new subject/topics into the interest profile."""
    try:
        ref = db.collection("student_interests").document(uid)
        doc = ref.get()
        existing = doc.to_dict() if doc.exists else {}
        subjects = existing.get("subjects", {})
        subjects[subject] = subjects.get(subject, 0) + 1
        all_topics = list(set(existing.get("topics", []) + topics))[-30:]
        ref.set({
            "subjects": subjects,
            "topics": all_topics,
            "last_updated": _now_ms(),
        }, merge=True)
    except Exception as exc:
        logger.warning("_update_interest_profile uid=%s: %s", uid, exc)


def _build_generation_prompt(interests: dict, existing_topics: list[str]) -> str:
    """Build the LLM prompt for generating today's questions."""
    top_subjects = sorted(
        interests.get("subjects", {}).items(), key=lambda x: -x[1]
    )[:3]
    top_topics = interests.get("topics", [])[:10]

    subjects_str = ", ".join(s for s, _ in top_subjects) if top_subjects else "Science, Math, History"
    topics_str = ", ".join(top_topics) if top_topics else "basic concepts"
    exclude_str = ", ".join(existing_topics[:10]) if existing_topics else "none"

    return f"""Generate exactly {QUESTIONS_PER_DAY} engaging daily learning questions for a student.

Student's top subjects: {subjects_str}
Recent topics studied: {topics_str}
Topics already used today (AVOID these): {exclude_str}

Rules:
- Each question must be thought-provoking and curiosity-driven (not "what is X")
- Mix difficulty levels (1 easy hook, 1 medium, 1 challenge)
- Make questions feel like natural wonders: "Why does...", "How does...", "What would happen if..."
- Keep each question under 15 words
- Cover different subjects / topics across the 3 questions

Return ONLY a JSON array with exactly {QUESTIONS_PER_DAY} objects. No markdown, no explanation.
Format:
[
  {{"question": "...", "subject": "...", "topic": "...", "difficulty": 1, "hook": "Did you know..."}},
  ...
]

difficulty: 1=easy, 2=medium, 3=hard
hook: one-line real-world curiosity fact related to the question (under 12 words)"""


# ── Models ────────────────────────────────────────────────────────────────────

class CompleteQuestionRequest(BaseModel):
    question_id: str
    bb_session_id: Optional[str] = ""


class RecordInterestRequest(BaseModel):
    subject: str
    topics: list[str] = []


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get("/feed")
async def get_daily_feed(auth: AuthUser = Depends(require_auth)):
    """
    Return today's questions for this user.
    If no questions exist for today, generate them now.
    Questions are lazy-generated on first fetch of the day.
    """
    uid = auth.uid
    db = get_firestore_db()
    if db is None:
        raise HTTPException(503, "Database unavailable")

    today = _today_utc()
    feed_ref = db.collection("daily_questions_feed").document(uid).collection("questions")

    # Try to load today's existing questions
    try:
        docs = feed_ref.where("date", "==", today).order_by("difficulty").get()
        questions = [{"id": d.id, **d.to_dict()} for d in docs]
    except Exception as exc:
        logger.warning("get_daily_feed fetch error uid=%s: %s", uid, exc)
        questions = []

    if len(questions) >= QUESTIONS_PER_DAY:
        return {"questions": questions, "generated": False, "date": today}

    # No questions yet for today — generate them
    try:
        loop = asyncio.get_event_loop()
        new_questions = await loop.run_in_executor(None, _generate_questions_sync, uid, db)
    except Exception as exc:
        logger.error("get_daily_feed generation error uid=%s: %s", uid, exc)
        new_questions = _fallback_questions()

    # Persist each question
    now = _now_ms()
    saved = []
    for q in new_questions:
        qid = str(uuid.uuid4())[:8]
        doc = {
            "question": q.get("question", ""),
            "subject": q.get("subject", "General"),
            "topic": q.get("topic", ""),
            "difficulty": int(q.get("difficulty", 1)),
            "hook": q.get("hook", ""),
            "date": today,
            "status": "pending",
            "created_at": now,
            "expires_at": now + QUESTION_TTL_HOURS * 3600 * 1000,
            "credits_reward": CREDITS_PER_COMPLETION,
        }
        feed_ref.document(qid).set(doc)
        saved.append({"id": qid, **doc})

    return {"questions": saved, "generated": True, "date": today}


def _generate_questions_sync(uid: str, db) -> list[dict]:
    """Synchronous LLM call — run in executor to avoid blocking the event loop."""
    interests = _get_interest_profile(db, uid)

    # Load topics used in the last 7 days to avoid repetition
    today = _today_utc()
    try:
        feed_ref = db.collection("daily_questions_feed").document(uid).collection("questions")
        recent = feed_ref.order_by("created_at", direction="DESCENDING").limit(20).get()
        existing_topics = [d.to_dict().get("topic", "") for d in recent if d.to_dict().get("topic")]
    except Exception:
        existing_topics = []

    prompt = _build_generation_prompt(interests, existing_topics)
    result = generate_response(prompt, tier="faster")

    if result.get("provider") == "error":
        return _fallback_questions()

    text = result.get("text", "").strip()
    # Extract JSON array from the response
    start = text.find("[")
    end = text.rfind("]") + 1
    if start < 0 or end <= start:
        return _fallback_questions()

    parsed = json.loads(text[start:end])
    if not isinstance(parsed, list) or len(parsed) == 0:
        return _fallback_questions()

    return parsed[:QUESTIONS_PER_DAY]


def _fallback_questions() -> list[dict]:
    """Static fallback in case LLM generation fails."""
    return [
        {"question": "Why does ice float on water?", "subject": "Science", "topic": "States of Matter", "difficulty": 1, "hook": "Ice saves fish in frozen lakes every winter"},
        {"question": "How does your brain store memories while you sleep?", "subject": "Biology", "topic": "Neuroscience", "difficulty": 2, "hook": "You replay your day 5× faster overnight"},
        {"question": "What would happen if gravity suddenly doubled on Earth?", "subject": "Physics", "topic": "Gravity", "difficulty": 3, "hook": "Skyscrapers would collapse in 8 minutes"},
    ]


@router.post("/complete")
async def complete_question(
    req: CompleteQuestionRequest,
    auth: AuthUser = Depends(require_auth),
):
    """
    Mark a daily question as completed and award credits.
    Idempotent — calling twice does not double-award.
    """
    uid = auth.uid
    db = get_firestore_db()
    if db is None:
        raise HTTPException(503, "Database unavailable")

    feed_ref = (
        db.collection("daily_questions_feed")
        .document(uid)
        .collection("questions")
        .document(req.question_id)
    )

    try:
        doc = feed_ref.get()
    except Exception as exc:
        raise HTTPException(500, f"Failed to load question: {exc}")

    if not doc.exists:
        raise HTTPException(404, "Question not found")

    data = doc.to_dict() or {}
    if data.get("status") == "completed":
        return {"credited": False, "message": "Already completed", "credits_earned": 0}

    credits = int(data.get("credits_reward", CREDITS_PER_COMPLETION))
    now = _now_ms()

    # Mark complete
    feed_ref.update({
        "status": "completed",
        "completed_at": now,
        "bb_session_id": req.bb_session_id or "",
    })

    # Award credits
    _award_credits(
        db=db,
        uid=uid,
        amount=credits,
        tx_type="daily_question",
        source_id=req.question_id,
        description=f"Completed: {data.get('question', '')[:60]}",
    )

    # Update interest profile from this question
    subject = data.get("subject", "General")
    topic = data.get("topic", "")
    if topic:
        _update_interest_profile(db, uid, subject, [topic])

    return {
        "credited": True,
        "credits_earned": credits,
        "message": f"+{credits} credits earned! 🎉",
    }


@router.get("/streak")
async def get_streak(auth: AuthUser = Depends(require_auth)):
    """Return the user's current completion streak (consecutive days with ≥1 completion)."""
    uid = auth.uid
    db = get_firestore_db()
    if db is None:
        raise HTTPException(503, "Database unavailable")

    try:
        docs = (
            db.collection("daily_questions_feed")
            .document(uid)
            .collection("questions")
            .where("status", "==", "completed")
            .order_by("completed_at", direction="DESCENDING")
            .limit(60)
            .get()
        )
        completed_dates = sorted(
            {
                datetime.fromtimestamp(d.to_dict().get("completed_at", 0) / 1000, tz=timezone.utc).strftime("%Y-%m-%d")
                for d in docs
                if d.to_dict().get("completed_at")
            },
            reverse=True,
        )
    except Exception as exc:
        logger.warning("get_streak uid=%s: %s", uid, exc)
        return {"streak": 0}

    if not completed_dates:
        return {"streak": 0}

    streak = 0
    today = datetime.now(tz=timezone.utc).date()
    for i, date_str in enumerate(completed_dates):
        expected = (today - __import__("datetime").timedelta(days=i)).strftime("%Y-%m-%d")
        if date_str == expected:
            streak += 1
        else:
            break

    return {"streak": streak}


@router.post("/interests")
async def record_interest(
    req: RecordInterestRequest,
    auth: AuthUser = Depends(require_auth),
):
    """
    Called by Android after each chat/BB session to keep the interest profile fresh.
    This drives personalised question generation.
    """
    db = get_firestore_db()
    if db is None:
        raise HTTPException(503, "Database unavailable")

    _update_interest_profile(db, auth.uid, req.subject, req.topics)
    return {"ok": True}


# ── Shared credit helper (also used by credits.py) ───────────────────────────

def _award_credits(
    db,
    uid: str,
    amount: int,
    tx_type: str,
    source_id: str = "",
    description: str = "",
) -> None:
    """
    Atomically add [amount] credits to user_credits/{uid} and append a transaction log entry.
    """
    if amount <= 0:
        return
    try:
        credits_ref = db.collection("user_credits").document(uid)
        credits_ref.set(
            {
                "balance": Increment(amount),
                "lifetime_earned": Increment(amount),
                "last_updated": _now_ms(),
            },
            merge=True,
        )
        tx_ref = db.collection("credit_transactions").document()
        tx_ref.set(
            {
                "uid": uid,
                "amount": amount,
                "type": tx_type,
                "source_id": source_id,
                "description": description,
                "created_at": _now_ms(),
            }
        )
    except Exception as exc:
        logger.warning("_award_credits uid=%s: %s", uid, exc)
